Gfx *geo_star_road_p(s32 callContext, struct GraphNode *node, UNUSED Mat4 mtx);
Gfx *geo_star_road_n(s32 callContext, struct GraphNode *node, UNUSED Mat4 mtx);

const GeoLayout Geo_castle_courtyard_1_0x2541700[]= {
GEO_NODE_SCREEN_AREA(10,160,120,160,120),
GEO_OPEN_NODE(),
GEO_ZBUFFER(0),
GEO_OPEN_NODE(),
GEO_NODE_ORTHO(100),
GEO_OPEN_NODE(),
GEO_BACKGROUND(SkyboxCustom39812800_skybox_Index+10, geo_skybox_main),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_ZBUFFER(1),
GEO_OPEN_NODE(),
GEO_CAMERA_FRUSTUM_WITH_FUNC(45,100,30000, geo_camera_fov),
GEO_OPEN_NODE(),
GEO_CAMERA(1,0,2000,6000,3072,0,60928, geo_camera_main),
GEO_OPEN_NODE(),
GEO_ASM(0, geo_star_road_p),
GEO_DISPLAY_LIST(LAYER_OPAQUE,DL_castle_courtyard_1_0xe072a00_n),
GEO_ASM(0, geo_star_road_p),
GEO_DISPLAY_LIST(LAYER_TRANSPARENT,DL_castle_courtyard_1_0xe08fbb0_n),
GEO_ASM(0, geo_star_road_n),
GEO_DISPLAY_LIST(LAYER_OPAQUE,DL_castle_courtyard_1_0xe072a00_p),
GEO_ASM(0, geo_star_road_n),
GEO_DISPLAY_LIST(LAYER_TRANSPARENT,DL_castle_courtyard_1_0xe08fbb0_p),
GEO_RENDER_OBJ(),
GEO_ASM(0, geo_envfx_main),
GEO_ASM(20480, geo_movtex_draw_water_regions),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_ZBUFFER(0),
GEO_OPEN_NODE(),
GEO_ASM(0, geo_cannon_circle_base),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_END(),
};
